### ISSUE TITLE
Create contacts page

### ISSUE THREAD

**Issue by gabororosz** [AppCraft-Projects/issues#11]
## Tasks

- [x] Create introduction text for each author
- [x] Create the layout for the contacts page (authors) and the author detail page
    - [x] List the entries of authors in the author detail page
    - [x] Link to author page from all entries
- [x] Add the `author` field to the frontmatter of all entries (posts and events)
- [x] Show link to contacts in header and footer
