### ISSUE TITLE
User registration & management

### ISSUE THREAD

**Issue by gabororosz** [AppCraft-Projects/issues#14]
## Tasks

- [x] Design brief
- [ ] Site design
- [ ] Only email & password
- [ ] Login trough social networks (eg. Facebook, Google) is not an option for us.
- [ ] Test Auth0 integration. Is free tier is enough for us?

**Some points to consider regarding GDPR:**
https://docs.google.com/document/d/1vdJ6D2gJ_Ulfhb-8ZQJK146pnQonC5MoVznZbQjqUpY/edit#
