### ISSUE TITLE
Comment on content

### ISSUE THREAD

**Issue by gabororosz** [AppCraft-Projects/issues#17]
## Tasks 

- [ ] Discuss several alternative solutions
- [ ] Design needed
- [ ] Comment on posts
- [ ] Comment on events
- [ ] Find out how to merge comment sections

**Interesting resource:**
- [Use GH issues as comments](https://www.richyhbm.co.uk/posts/using-github-issues-as-comments-for-a-static-site/)
