### ISSUE TITLE
SEO focus

### ISSUE THREAD

**Issue by bruce-forte** [AppCraft-Projects/issues#8]
## Requirements
All pages need to have necessary SEO information and format
- [x] `meta` tags
- [x] no keyword stuffing
- [x] pretty urls
- [x] desciptive names
- [x] good first paragraphs (which appears in Google)
- [x] canonical content
- [x] change title | sitename order

## Tasks

- [x] We need to flesh out the details of the link pyramid
