### ISSUE TITLE
Full text search functionality

### ISSUE THREAD

**Issue by gabororosz** [AppCraft-Projects/issues#9]
## Tasks

- [x] Design brief
- [x] Site design 
- [x] Search bar in header
- [x] Search result page

This provider looks good, we may can integrate it: https://community.algolia.com/docsearch/

**Regarding Algolia**
- [x] We need to upload our content in JSON format to their API
- [x] We need a server(less) environment to handle this issue

**Fixes**
- [x] Fix padding, there isn't enough space at the bottom of the card: https://imgur.com/Rp4RhqO
- [x] Text owerflow: https://imgur.com/9qmaGh6

**Resources:**
- [GitHub webhooks when we push a new content to the repo](https://developer.github.com/webhooks/)
- [We can use Microsoft Azure.](https://azure.microsoft.com/en-us/roadmap/java-support-for-azure-functions/)
- [Or AWS Lambda](https://aws.amazon.com/lambda/?sc_channel=PS&sc_campaign=acquisition_HU&sc_publisher=google&sc_medium=english_lambda_b&sc_content=lambda_p&sc_detail=aws%20lambda&sc_category=lambda&sc_segment=225268211456&sc_matchtype=p&sc_country=HU&s_kwcid=AL!4422!3!225268211456!p!!g!!aws%20lambda&ef_id=WwKu1QAAAKXPVGjc:20180628084028:s).
- [Using GraalVM + Kotlin can be also interesting.](https://www.richyhbm.co.uk/posts/compiling-kotlin-netty-webapp-with-graalvm/)

**Comment by bruce-forte** [comment]
I sent a request to algolia, we are waiting for their response

**Comment by bruce-forte** [comment]
We didn't need the serverless environment after all, since the `jekyll-algolia` plugin handles the upload when building the site. 👍

**Comment by gabororosz** [comment]
Found some CSS issue:
- Typed keyword "Teszt" into searchbox, some result cards are broken, text overflow (Tested on Mac, both with Safari and Chrome) - https://imgur.com/a/lBsVdEb 
- Text overflows from cards in iOS Safari - https://imgur.com/a/A1Y9jZ1
